### ISSUE TITLE
Missing information for optimal-life

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Optimal-Life-Lp#1]
i am missing 
1. domain.
2. clients email.
thanks.

**Comment by talovdat** [comment]
1. B-SLIM.CO.IL
2. contact@Optimali.co.il
*Back up mail addres : lidim@bwell.co.il

You welcome.

**Comment by MeanEYE** [comment]
I'd appreciate @talovdat if we were not responsible for getting our client's email address to spam lists. Send things like these through email.
