### ISSUE TITLE
On mobile version contant sticks to the right 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Optimal-Life-Lp#18]
On the mobile version the contant sticks to the right. 

![whatsapp image 2017-05-25 at 13 47 50](https://cloud.githubusercontent.com/assets/26923359/26447505/7b6f7f74-4151-11e7-8736-153c9ffa32ae.jpeg)

**Comment by MeanEYE** [comment]
Assigned to @iliyaM even though I have no idea what Tal wanted to say. Should the text be aligned, or it's aligned and it doesn't have to be.

**Comment by iliyaM** [comment]
I have no idea if he is talking about lightbox content or some other section on the site. 
this is my version of light box. ill check on read device aswell.

![screenshot from 2017-05-25 14-07-39](https://cloud.githubusercontent.com/assets/20294485/26447954/9fcbf274-4153-11e7-8b28-362dc8e42b14.png)

**Comment by iliyaM** [comment]
All god on live version too
@talovdat please explain

**Comment by talovdat** [comment]
Some how when i check b-slim on my mobile, all the text sticks to the right but when i check on my computer and through inspect mobile mode it's fine. Did i manage to explain my self alright?
No light box, only the contant along the page. even the picture sticks to the right. again, only on my moblie.

**Comment by talovdat** [comment]
My phone is fucked up. sorry for wasted you time.
