### ISSUE TITLE
Change black logo to colored one.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Optimal-Life-Lp#20]
The logo is black, Change it to original colerized logo.
File in Drive.

![image](https://user-images.githubusercontent.com/26923359/27122571-ce401ef0-50f3-11e7-98b6-27a79292003a.png)

**Comment by MeanEYE** [comment]
This is something they specifically asked for. Logo is being A/B tested.

**Comment by talovdat** [comment]
Cant we do A/B testing with original logo?

**Comment by MeanEYE** [comment]
We are doing it. You are just seeing black version. If you look at someone else's computer you'll most likely see colored one.

**Comment by talovdat** [comment]
We need to do A/B testing with two colored logos, Nun of them should be black.
