### ISSUE TITLE
Something is wrong with gallery?

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Optimal-Life-Lp#6]
![screenshot from 2017-05-17 10-08-17](https://cloud.githubusercontent.com/assets/20294485/26142334/c4605e98-3ae8-11e7-8dcf-86361a1ae18b.png)

**Comment by MeanEYE** [comment]
Yeah, am redoing the lightbox. And no sites should us develop version. I'll have to fix! Thanks.
