### ISSUE TITLE
Missing favicon.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Optimal-Life-Lp#8]
![image](https://cloud.githubusercontent.com/assets/1911594/26283676/c727c7aa-3e2c-11e7-8dbc-a460691e7516.png)
Somehow not even default favicon is being displayed. Please make sure there's favicon defined.

**Comment by MeanEYE** [comment]
Issue is same as Way2CU/Cybcast#8.

**Comment by iliyaM** [comment]
Same issue with cybcast. naming :/
